### PR TITLE
Pin markupsafe at 1.1.1

### PR DESCRIPTION
**Pull request by kedarv**
Fixes odd build issues with markupsafe 2.0.0a1 (relates to https://github.com/pallets/markupsafe/issues/119)

### CODE REVIEW

**Comment by asottile** [comment]
this isn't correct, yelp-cheetah works fine with markupsafe 2.x

**Comment by asottile** [comment]
fwiw, you're probably either using (1) an old version of pip which doesn't properly understand `python_requires` or (2) `easy_install` (which is super deprecated)

modern versions of pip will avoid installing `markupsafe>=2a0` because it provides [this metadata](https://github.com/pallets/markupsafe/blob/ce2e28b599013dbc596e84d58647f4abafc83901/setup.cfg#L30)

**Comment by fzxt** [comment]
@asottile 

(1) we're using pip 9.x, i think this is recent enough to support python_requires
(2) we're not using easy_install

could the issue be that yelp_cheetah suggests using `setup_requires`, which instead uses `setuptools` instead of `pip`?

to add some context, this is blocking a few builds at yelp right now, so i think we should consider reopening this pull request and creating an issue in the appropriate repo to support installing `markupsafe` correctly

**Comment by asottile** [comment]
I suspect your actual bug is your index doesn't support python-requires

please don't break this package -- you should pin your dependencies instead (for instance via `requirements.txt` or `additional_requirements`)

**Comment by asottile** [comment]
it is possible if you're getting this through `setup_requires` and using an old version of `setuptools` (that will go through `easy_install`) -- if you're using `setuptools>=42` it will use pip

**Pull request closed without merging**
